# Generated by Django 5.2.6 on 2025-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_monthly_income_user_ward_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=100)),
            ],
        ),
    ]
