# Generated by Django 5.2.6 on 2025-10-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_homemenu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('user', 'card_type', 'item_name', 'month')},
        ),
    ]
