# Generated by Django 5.2.6 on 2025-10-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_entitlement_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('card_type', 'item_name', 'month')},
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='user',
        ),
    ]
