# Generated by Django 5.2.6 on 2025-10-09 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_entitlement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together={('card_type', 'month')},
        ),
        migrations.AddField(
            model_name='entitlement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shopadmin'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='updated_at',
        ),
    ]
