# Generated by Django 5.2.6 on 2025-10-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_entitlement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitlement',
            name='month',
            field=models.IntegerField(),
        ),
    ]
