# Generated by Django 5.2.6 on 2025-10-10 01:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_entitlement_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='card_type',
            field=models.CharField(choices=[('APL', 'APL'), ('BPL', 'BPL'), ('AAY', 'Antyodaya'), ('PHH', 'PHH')], default='APL', max_length=10),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='shop',
            field=models.ForeignKey(db_column='shop_id', on_delete=django.db.models.deletion.CASCADE, to='api.shopadmin', to_field='shop_id'),
        ),
    ]
