# Generated by Django 5.2.6 on 2025-10-11 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_stockitem_updated_at_stockitem_card_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entitlement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shopadmin',
            name='panchayath',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='shop',
        ),
        migrations.AddField(
            model_name='entitlement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='panchayath_shop',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='shopadmin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shopadmin'),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='card_type',
            field=models.CharField(choices=[('APL', 'APL'), ('BPL', 'BPL'), ('PHH', 'PHH'), ('AAY', 'AAY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='month',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='entitlement',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='card_type',
            field=models.CharField(choices=[('APL', 'APL'), ('BPL', 'BPL'), ('AAY', 'Antyodaya'), ('PHH', 'PHH')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='entitlement',
            name='created_by',
        ),
    ]
