# Generated by Django 5.2.6 on 2025-10-11 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_entitlement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shopadmin'),
        ),
    ]
