# Generated by Django 5.2.6 on 2025-10-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_entitlement_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopadmin',
            name='panchayath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
