# Generated by Django 5.2.6 on 2025-10-12 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_shopadmin_panchayath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='panchayath_shop',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='shopadmin',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shopadmin'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
