# Generated by Django 5.2.6 on 2025-10-12 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_stockitem_card_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopstatus',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='shopstatus',
            name='region',
        ),
        migrations.AddField(
            model_name='shopstatus',
            name='location',
            field=models.CharField(default='Not specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopstatus',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Not specified', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopstatus',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='api.shopadmin'),
        ),
    ]
