# Generated by Django 5.2.6 on 2025-10-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_shopstatus_is_open_remove_shopstatus_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstatus',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
