# Generated by Django 5.2.6 on 2025-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_owner_remove_entitlement_shop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
