# Generated by Django 5.2.6 on 2025-10-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_monthlyentitlement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyEntitlement',
            new_name='Entitlement',
        ),
    ]
