# Generated by Django 5.2.6 on 2025-10-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_shop_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='card_type',
            field=models.CharField(choices=[('BPL', 'BPL'), ('APL', 'APL'), ('PHH', 'PHH')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
