# Generated by Django 5.2.6 on 2025-10-16 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_shop_name_remove_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=150),
        ),
    ]
