# Generated by Django 5.2.6 on 2025-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_shop_created_at_shop_updated_at_alter_shop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
