# Generated by Django 5.2.6 on 2025-10-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_stock_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='location',
        ),
    ]
