# Generated by Django 5.2.6 on 2025-10-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_stock_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='available_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='card_type',
            field=models.CharField(choices=[('BPL', 'BPL'), ('APL', 'APL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
    ]
