# Generated by Django 5.2.6 on 2025-10-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_stock_available_quantity_alter_stock_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(default='SHP001', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.shop'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('shop', 'card_type', 'item_name')},
        ),
    ]
