# Generated by Django 5.2.6 on 2025-10-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_shop_shop_code_alter_stock_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
