# Generated by Django 5.2.6 on 2025-10-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_shop_location_alter_shop_owner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
