# Generated by Django 5.2.6 on 2025-10-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_shop_owner_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_place',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='available_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='card_type',
            field=models.CharField(choices=[('APL', 'APL'), ('BPL', 'BPL')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='updated_at',
        ),
    ]
