# Generated by Django 5.2.6 on 2025-10-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_user_rationuser_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='ration_user',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
